### ISSUE TITLE
Addon not installing in ember-cli

### ISSUE THREAD

**Issue by jamesmenera** [trentmwillis/ember-a11y-testing#1]
jamesmenera@MacBook-Pro:~/Sites/Acorns-ember[develop*]$ ember install ember-a11y-testing
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
installing
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by trentmwillis** [comment]
This is an issue with Ember-CLI itself. The add-on should have installed properly even if you get the message. Issue for reference: https://github.com/ember-cli/ember-cli/pull/3846
